version: "3.9"  # optional since v1.27.0
services:
  elasticsearch:
    image: library/elasticsearch:5.6.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - atlas-test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  #atlas:
  #  build:
  #   context: atlas
  #   dockerfile: ./Dockerfile
  # entrypoint: /opt/apache-atlas-2.1.0/bin/atlas_start.py
  # container_name: atlas
  # ports:
  #   - "21000:21000"
  # networks:
  #   - atlas-test
  # depends_on:
  #   elasticsearch:
  #     condition: service_healthy

  atlas_sburn:
    build:
      context: docker-apache-atlas
      dockerfile: ./Dockerfile
    entrypoint: /opt/apache-atlas-2.1.0/bin/atlas_start.py
    container_name: atlas_sburn
    ports:
      - "21000:21000"
    networks:
      - atlas-test
    depends_on:
      elasticsearch:
        condition: service_healthy

networks:
  atlas-test:
    driver: bridge
