version: "3.9"  # optional since v1.27.0
services:
  elasticsearch:
    image: library/elasticsearch:6.7.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - lgpd
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra:
    image: cassandra:3.11.10
    container_name: cassandra
    ports:
      - "7000:7000"
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra
      - CASSANDRA_SEEDS=cassandra
    networks:
      - lgpd
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 30s
      timeout: 10s
      retries: 10

  zookeeper:
    image: zookeeper:3.4.9
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
      - ZOO_PORT=2181
      - ZOO_SERVERS=server.1=zookeeper:2888:3888
    networks:
      - lgpd
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    networks:
      - lgpd
    depends_on:
      - zookeeper
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 30s
      timeout: 10s
      retries: 4

  atlas:
    build:
      context: atlas
      dockerfile: ./Dockerfile
    entrypoint: /opt/atlas/bin/atlas_start.py
    container_name: atlas
    ports:
      - "21000:21000"
    networks:
      - lgpd
    depends_on:
      elasticsearch:
        condition: service_healthy
      cassandra:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

networks:
  lgpd:
    driver: bridge
