version: "3.9"  # optional since v1.27.0
services:
  elasticsearch:
    image: library/elasticsearch:6.7.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - atlas-test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra:
    image: cassandra:3.11.10
    container_name: cassandra
    ports:
      - "7000:7000"
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra
      - CASSANDRA_SEEDS=cassandra
    networks:
      - atlas-test
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60


  atlas:
    build:
      context: atlas
      dockerfile: ./Dockerfile
    entrypoint: /opt/atlas/bin/atlas_start.py
    container_name: atlas
    ports:
      - "21000:21000"
    networks:
      - atlas-test
    depends_on:
      elasticsearch:
        condition: service_healthy
      cassandra:
        condition: service_healthy
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

networks:
  atlas-test:
    driver: bridge
